# SPDX-FileCopyrightText: Copyright (c) 2022 Objectionary
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: codecov
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  codecov:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g eolang
      - run: mvn install -Pjacoco
      - uses: codecov/codecov-action@v5
        with:
          file: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
